# http://docs.confluent.io/current/cp-docker-images/docs/configuration.html
---
version: '2.1'
services:
  influxdb:
    image: influxdb:1.5.4
    hostname: influxdb
    expose:
      - "8086"
      - "8083"
    ports:
      - "8083:8083"
      - "8086:8086"
#    volumes:
#      - ~/data/influxdb:/var/lib/influxdb  
    environment:
      PRE_CREATE_DB: misc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:5.2.1
    hostname: grafana
    depends_on:
      influxdb: { condition: service_healthy }
    ports:
      - "3000:3000"
#    volumes:
#      - ~/data/grafana:/var/lib/grafana
