# http://docs.confluent.io/current/cp-docker-images/docs/configuration.html
# https://docs.confluent.io/current/installation/docker/docs/config-reference.html
---
version: '2.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0-2
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_SYNC_LIMIT: 2
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3

  broker:
    image: confluentinc/cp-kafka:5.0.0-2
    hostname: broker
    depends_on:
      zookeeper: { condition: service_healthy }
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'
      # Comment for manual creation
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
#      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:9092
#      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
#      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
#      CONFLUENT_METRICS_ENABLE: 'true'
#      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka_rest:
    image: confluentinc/cp-kafka-rest:5.0.0-1
    hostname: kafka_rest
    depends_on:
      - zookeeper
      - schema_registry
      - broker
    ports:
      - "8082:8082"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      KAFKA_REST_LISTENERS: 'http://kafka_rest:8082'
      KAFKA_REST_HOST_NAME: 'kafka_rest'

#  kafka-topics-ui:
#    image: landoop/kafka-topics-ui:0.9.4
#    hostname: kafka-topics-ui
#    ports:
#      - "8000:8000"
#    environment:
#      KAFKA_REST_PROXY_URL: 'http://kafka_rest:8082'
#      PROXY: 'true'

  schema_registry:
    image: confluentinc/cp-schema-registry:5.0.0-1
    hostname: schema_registry
    depends_on:
      broker: { condition: service_healthy }
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
#      SCHEMA_REGISTRY_LISTENERS: 'http://schema_registry:8081'
#      SCHEMA_REGISTRY_DEBUG: "true"

  schema_registry_ui:
   image: landoop/schema-registry-ui:0.9.5
   hostname: schema_registry_ui
   ports:
     - "8000:8000"
   environment:
      SCHEMAREGISTRY_URL: 'http://schema_registry:8081'
      PROXY: 'true'
      ALLOW_GLOBAL: 1
#      ALLOW_TRANSITIVE: 1
#      PROXY_SKIP_VERIFY: 'true'
